---
apiVersion: http.crossplane.io/v1alpha2
kind: DisposableRequest
metadata:
  name: test-nexus-fcp-profiles-tls
spec:
  deletionPolicy: Orphan
  forProvider:
    url: >-
      https://nexus-adp-dev.regional.devops-services.gwc1.azure.aztec.cloud.allianz/repository/AZD-Whitelist/ct1ger_fcp_profiles.yaml
    method: GET
    insecureSkipTLSVerify: false
    headers:
      Accept:
        - application/x-yaml
        - text/yaml
  providerConfigRef:
    name: http-tls
